# Change these first
owner: activitar # Your GitHub organization or username, where this repository lives
repo: status.activitar.com # The name of this repository

assignees: # Users to assign downtime issues (optional)
  - chriscz
  - alexleid
  - janineab
sites:
  - name: Activitar Management Platform
    ulr: https://new.activitar.com

  - name: Activitar Portal
    url: https://activitar.com

  - name: Activitar Corporate
    url: https://www.activitar.net


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.activitar.com
  # baseUrl: /your-repo-name
  logoUrl: https://www.activitar.net/assets/img/logo_no_slogan.png
  name: Activitar
  introTitle: "Status Page for Activitar, Africa's Leading Adventure Management Platform"
  introMessage: The Activitar team does its best to keep the Activitar platform operational 24/7, 365. But when technical issues do arise, we think our customers deserve clear, transparent communication so they can maintain trust in our service and our team. Notices will be posted here when we re-route traffic, upgrade hardware, or in the case where our services are inaccessible. If you are experiencing issues and do not see a notice posted, please email support@activitar.com for assistance.
  navbar:
    - title: Status
      href: /
    - title: Activitar Management System
      href: https://new.activitar.com
    - title: Activitar Portal
      href: https://activitar.com
    - title: Activitar Corporate
      href: https://www.activitar.net
      #    - title: GitHub
#      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
